// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graph.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GraphObject struct {
	AdjacencyList        map[int32]*Neighbors `protobuf:"bytes,1,rep,name=adjacencyList,proto3" json:"adjacencyList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GraphObject) Reset()         { *m = GraphObject{} }
func (m *GraphObject) String() string { return proto.CompactTextString(m) }
func (*GraphObject) ProtoMessage()    {}
func (*GraphObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{0}
}

func (m *GraphObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphObject.Unmarshal(m, b)
}
func (m *GraphObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphObject.Marshal(b, m, deterministic)
}
func (m *GraphObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphObject.Merge(m, src)
}
func (m *GraphObject) XXX_Size() int {
	return xxx_messageInfo_GraphObject.Size(m)
}
func (m *GraphObject) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphObject.DiscardUnknown(m)
}

var xxx_messageInfo_GraphObject proto.InternalMessageInfo

func (m *GraphObject) GetAdjacencyList() map[int32]*Neighbors {
	if m != nil {
		return m.AdjacencyList
	}
	return nil
}

type Neighbors struct {
	Nodes                []int32  `protobuf:"varint,1,rep,packed,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Neighbors) Reset()         { *m = Neighbors{} }
func (m *Neighbors) String() string { return proto.CompactTextString(m) }
func (*Neighbors) ProtoMessage()    {}
func (*Neighbors) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{1}
}

func (m *Neighbors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Neighbors.Unmarshal(m, b)
}
func (m *Neighbors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Neighbors.Marshal(b, m, deterministic)
}
func (m *Neighbors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Neighbors.Merge(m, src)
}
func (m *Neighbors) XXX_Size() int {
	return xxx_messageInfo_Neighbors.Size(m)
}
func (m *Neighbors) XXX_DiscardUnknown() {
	xxx_messageInfo_Neighbors.DiscardUnknown(m)
}

var xxx_messageInfo_Neighbors proto.InternalMessageInfo

func (m *Neighbors) GetNodes() []int32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type CreateGraphResponse struct {
	GraphID              int32    `protobuf:"varint,1,opt,name=graphID,proto3" json:"graphID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGraphResponse) Reset()         { *m = CreateGraphResponse{} }
func (m *CreateGraphResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGraphResponse) ProtoMessage()    {}
func (*CreateGraphResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{2}
}

func (m *CreateGraphResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGraphResponse.Unmarshal(m, b)
}
func (m *CreateGraphResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGraphResponse.Marshal(b, m, deterministic)
}
func (m *CreateGraphResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGraphResponse.Merge(m, src)
}
func (m *CreateGraphResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGraphResponse.Size(m)
}
func (m *CreateGraphResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGraphResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGraphResponse proto.InternalMessageInfo

func (m *CreateGraphResponse) GetGraphID() int32 {
	if m != nil {
		return m.GraphID
	}
	return 0
}

func init() {
	proto.RegisterType((*GraphObject)(nil), "api.GraphObject")
	proto.RegisterMapType((map[int32]*Neighbors)(nil), "api.GraphObject.AdjacencyListEntry")
	proto.RegisterType((*Neighbors)(nil), "api.Neighbors")
	proto.RegisterType((*CreateGraphResponse)(nil), "api.CreateGraphResponse")
}

func init() { proto.RegisterFile("graph.proto", fileDescriptor_3e4c656902fc0e6b) }

var fileDescriptor_3e4c656902fc0e6b = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2f, 0x4a, 0x2c,
	0xc8, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x5a, 0xc5, 0xc8,
	0xc5, 0xed, 0x0e, 0x12, 0xf4, 0x4f, 0xca, 0x4a, 0x4d, 0x2e, 0x11, 0xf2, 0xe4, 0xe2, 0x4d, 0x4c,
	0xc9, 0x4a, 0x4c, 0x4e, 0xcd, 0x4b, 0xae, 0xf4, 0xc9, 0x2c, 0x2e, 0x91, 0x60, 0x54, 0x60, 0xd6,
	0xe0, 0x36, 0x52, 0xd6, 0x4b, 0x2c, 0xc8, 0xd4, 0x43, 0x52, 0xa8, 0xe7, 0x88, 0xac, 0xca, 0x35,
	0xaf, 0xa4, 0xa8, 0x32, 0x08, 0x55, 0xa7, 0x54, 0x00, 0x97, 0x10, 0xa6, 0x22, 0x21, 0x01, 0x2e,
	0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x10, 0x53, 0x48, 0x85, 0x8b,
	0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0xdb, 0x88, 0x0f, 0x6c, 0x95,
	0x5f, 0x6a, 0x66, 0x7a, 0x46, 0x52, 0x7e, 0x51, 0x71, 0x10, 0x44, 0xd2, 0x8a, 0xc9, 0x82, 0x51,
	0x49, 0x91, 0x8b, 0x13, 0x2e, 0x2e, 0x24, 0xc2, 0xc5, 0x9a, 0x97, 0x9f, 0x92, 0x5a, 0x0c, 0x76,
	0x21, 0x6b, 0x10, 0x84, 0xa3, 0xa4, 0xcf, 0x25, 0xec, 0x5c, 0x94, 0x9a, 0x58, 0x92, 0x0a, 0x76,
	0x6b, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x04, 0x17, 0x3b, 0xd8, 0xeb, 0x9e,
	0x2e, 0x50, 0x9b, 0x61, 0x5c, 0x23, 0x6f, 0x2e, 0x1e, 0xa8, 0xd2, 0xc2, 0xd2, 0xd4, 0xe2, 0x12,
	0x21, 0x6b, 0x2e, 0x6e, 0x24, 0x03, 0x84, 0x04, 0xd0, 0x3d, 0x2e, 0x25, 0x01, 0x16, 0xc1, 0x62,
	0x89, 0x12, 0x43, 0x12, 0x1b, 0x38, 0x64, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x57, 0xe5,
	0x86, 0x1a, 0x68, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GraphRequestClient is the client API for GraphRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GraphRequestClient interface {
	CreateGraph(ctx context.Context, in *GraphObject, opts ...grpc.CallOption) (*CreateGraphResponse, error)
}

type graphRequestClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphRequestClient(cc grpc.ClientConnInterface) GraphRequestClient {
	return &graphRequestClient{cc}
}

func (c *graphRequestClient) CreateGraph(ctx context.Context, in *GraphObject, opts ...grpc.CallOption) (*CreateGraphResponse, error) {
	out := new(CreateGraphResponse)
	err := c.cc.Invoke(ctx, "/api.GraphRequest/CreateGraph", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphRequestServer is the server API for GraphRequest service.
type GraphRequestServer interface {
	CreateGraph(context.Context, *GraphObject) (*CreateGraphResponse, error)
}

// UnimplementedGraphRequestServer can be embedded to have forward compatible implementations.
type UnimplementedGraphRequestServer struct {
}

func (*UnimplementedGraphRequestServer) CreateGraph(ctx context.Context, req *GraphObject) (*CreateGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGraph not implemented")
}

func RegisterGraphRequestServer(s *grpc.Server, srv GraphRequestServer) {
	s.RegisterService(&_GraphRequest_serviceDesc, srv)
}

func _GraphRequest_CreateGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphRequestServer).CreateGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GraphRequest/CreateGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphRequestServer).CreateGraph(ctx, req.(*GraphObject))
	}
	return interceptor(ctx, in, info, handler)
}

var _GraphRequest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GraphRequest",
	HandlerType: (*GraphRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGraph",
			Handler:    _GraphRequest_CreateGraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graph.proto",
}
